'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ATPunchClock
    
    '''<summary>
    '''AjaxManagerGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AjaxManagerGeneral As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''PnlGridContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlGridContent As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''NetsoftContentBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NetsoftContentBox1 As Global.Osi.AlChavo.Common.Controls.NetsoftContentBox
    
    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ppadtxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppadtxt As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''ContentTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Lidepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lidepartment As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''DdlDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlDepartments As Global.Osi.AlChavo.Common.Controls.NetsoftComboBox
    
    '''<summary>
    '''lblPunchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPunchName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LnkBtnBottomPunchIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkBtnBottomPunchIN As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LnkBtnBottomPunchOUT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkBtnBottomPunchOUT As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''RegularExpressionValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblBadDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBadDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInvalidPunch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvalidPunch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCouldNotPunch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCouldNotPunch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWrongPIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWrongPIN As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCompanyPayrollStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyPayrollStart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPunchComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPunchComplete As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFirstPunch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstPunch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDPunches control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDPunches As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMinimunDist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMinimunDist As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNoGeoLocationAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoGeoLocationAvailable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAutopunchDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutopunchDone As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hidPunchType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPunchType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidPunchOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPunchOrder As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidTime As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdGeoEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdGeoEnable As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdCamEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCamEnable As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdLat As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdLong As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdPhoto As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdLateNot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdLateNot As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdArrivalNot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdArrivalNot As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdLateMins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdLateMins As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdMissingNOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdMissingNOT As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdAbsentNOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdAbsentNOT As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdEarlyArrivalNOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdEarlyArrivalNOT As Global.System.Web.UI.WebControls.HiddenField
End Class
